style: github
template: CHANGELOG.tpl.md
info:
  title: Changelog
  repository_url: https://github.com/needo37/filabridge
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - chore
        - docs
        - style
        - refactor
        - bug
  commit_groups:
    title_maps:
      feat: Added
      fix: Fixed
      bug: Fixed
      chore: Changed
      docs: Documentation
      style: Changed
      refactor: Changed
  header:
    pattern: "^(feat|fix|chore|docs|style|refactor|bug):"
    pattern_maps:
      - Type